host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv

runtime_environments:
    - name: python38
      operating_system:
          name: ubi
          version: "8"
      python_version: "3.8"
      recommendation_type: latest

managers:
    - name: thoth-advise
      configuration:
          labels: [bot]
    - name: info
    - name: version
      configuration:
          maintainers:
              - mimotej
              - sesheta
              - tumido
          assignees:
              - sesheta
          labels: [bot]
          changelog_file: true
          changelog_smart: true
