title: Hitchhiker's Guide to Operate First
author: "Operate first"
copyright: "2021"
logo: img/icon.png
execute:
  execute-notebooks: "off"
only_build_toc_files: true
html:
  favicon: img/favicon.png
repository:
  url: https://github.com/operate-first/hitchhikers-guide
  branch: main
